### ISSUE TITLE
multi_extract no function clause matching   "def to_charlist(string) when is_binary(string)"

### ISSUE THREAD

**Issue by kbrown-axio** [jsonkenl/xlsxir#123]
I'm seeing an unexpected behavior with a particular spreadsheet.  Will updated as I discover possible if there is anything particular about this spreadsheet.  

iex(3)> {:ok, tid} = Xlsxir.multi_extract(xlsx_file)
** (FunctionClauseError) no function clause matching in String.to_charlist/1    
    
    The following arguments were given to String.to_charlist/1:
    
        # 1
        %Xlsxir.XlsxFile{
          worksheet_xml_files: [
            %Xlsxir.XmlFile{
              name: "sheet4.xml",
              path: nil,
              content: "<?xml version=\"1.0\" encoding=\"UTF-8\" ...
            },
            %Xlsxir.XmlFile{
              name: "sheet1.xml",
              path: nil,
              content: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/ ...
            },
            %Xlsxir.XmlFile{
              name: "sheet2.xml",
              path: nil,
              content: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/ <> ...
            }
          ],
          shared_strings_xml_file: %Xlsxir.XmlFile{
            name: "sharedStrings.xml",
            path: nil,
            content: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n<sst <> ...
          },
          styles_xml_file: %Xlsxir.XmlFile{
            
            ...

            F\"/><xcalcf:feature name=\"microsoft.com:LAMBDA_WF\"/><xcalcf:feature name=\"microsoft.com:ARRAYTEXT_WF\"/></xcalcf:calcFeatures></ext></extLst></workbook>"
          },
          styles: #Reference<0.253553389.3350331393.1920>,
          workbook: #Reference<0.253553389.3350331393.1922>,
          shared_strings: #Reference<0.253553389.3350331393.1915>,
          max_rows: nil,
          extract_to: :memory,
          extract_dir: nil,
          options: []
        }
    
    Attempted function clauses (showing 1 out of 1):
    
        def to_charlist(string) when is_binary(string)
    
    (elixir 1.15.4) lib/string.ex:2577: String.to_charlist/1
    (xlsxir 1.6.4) lib/xlsxir/unzip.ex:70: Xlsxir.Unzip.validate_path_all_indexes/1
    (xlsxir 1.6.4) lib/xlsxir/xlsx_file.ex:231: Xlsxir.XlsxFile.extract_all_xml_files/2
    (xlsxir 1.6.4) lib/xlsxir/xlsx_file.ex:63: Xlsxir.XlsxFile.initialize/2
    (xlsxir 1.6.4) lib/xlsxir.ex:229: Xlsxir.multi_extract/5
    iex:3: (file)

**Comment by kbrown-axio** [comment]
Update: Same behavior on new spreadsheet with 2 cells.  So could be a dependency or environmental problem.  🤷

**Comment by kbrown-axio** [comment]
Update: "path: nil"  looks **sus** especially given:

Attempted function clauses (showing 1 out of 1):

    def to_charlist(string) when is_binary(string)

(elixir 1.15.4) lib/string.ex:2577: String.to_charlist/1
(xlsxir 1.6.4) lib/xlsxir/unzip.ex:70: Xlsxir.Unzip.validate_path_all_indexes/1

**Comment by kbrown** [comment]
working now.   errors are not informative if the application has not been started.

**Comment by jsonkenl** [comment]
Thanks for confirming this is working. For explicit startup, use
`Application.ensure_all_started(:xlsxir)`, then pass a filename string to
`Xlsxir.multi_extract/1`. Without a sheet index the result is a list of
`{:ok, tid}` entries; with index 0 it is one tuple. Close each returned table
with `Xlsxir.close/1` after use. A nil XmlFile path is expected for memory
extraction. The posted trace contains a struct where a filename is expected,
so it does not independently establish the startup cause. We are treating
the original incident as resolved by your follow-up and carrying clearer
startup/usage documentation into the #119 maintenance work.
